# Generated by Django 5.1.2 on 2024-12-21 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_shoesizeavailability_gender'),
        ('orders', '0003_order_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.shoesize'),
        ),
    ]
