# Generated by Django 5.1.2 on 2024-11-26 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeSizeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shoes')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shoesize')),
            ],
            options={
                'unique_together': {('shoe', 'size')},
            },
        ),
    ]
