# Generated by Django 5.1.2 on 2024-12-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_shoesizeavailability_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('M', 'Мужская'), ('Ж', 'Женская')], max_length=1, unique=True, verbose_name='Категория пола')),
            ],
        ),
    ]
