# Generated by Django 5.1.2 on 2024-12-21 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='gender_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoes', to='main.gender', verbose_name='Пол'),
        ),
    ]
