# Generated by Django 5.1.2 on 2024-12-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_shoes_gender_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoes',
            options={'verbose_name': 'Обувь'},
        ),
    ]
