# Generated by Django 5.1.2 on 2024-12-21 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_shoes_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='gender_category',
        ),
        migrations.CreateModel(
            name='ShoeGenderAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Доступное количество')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gender')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender_availabilities', to='main.shoes')),
            ],
            options={
                'verbose_name': 'Доступность обуви по полу',
                'verbose_name_plural': 'Доступности обуви по полу',
            },
        ),
    ]
