# Generated by Django 5.1.2 on 2024-12-21 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_shoes_gender_category_shoegenderavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoesizeavailability',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.gender'),
        ),
    ]
