# Generated by Django 5.1.2 on 2024-12-22 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_shoesizeavailability_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.gender', verbose_name='Пол'),
        ),
    ]
